### ISSUE TITLE
Mots avec accents

### ISSUE THREAD

**Issue by GlitchiKun** [MisterRobot42/quesaquo_motchus#1]
Oh Fatche !

Ton script il pétarde pas si le mot il a un accent cong !

Arrête de moularder et corrige nous ça minot

**Comment by TheCactusVert** [comment]
Oh tu fais un script mais t'as pas l'accent du sud, fatche con.

**Comment by MisterRobot42** [comment]
Oï, les collègues,

Tenez-vous bien, j'ai une new top moumoute pour vous ! Ce fichu bug avec les accents sur notre script Motchus, il a pris le large, il s'est fait la malle ! On a bidouillé comme des chefs et maintenant, le script, il gère les mots, qu'ils aient des accents ou pas, comme un vrai boss. Que ce soit "bédoule" ou "BEDOULE", ça passe comme une lettre à La Poste.

Faites donc une tite vérif de votre côté pour voir si tout roule, mais normalement, c'est aussi bon que du pastis après la pétanque. On a rajouté une petite astuce de derrière les fagots qui transforme les mots avec des accents en mots sans, et comme ça, pas de galère entre les deux. Ça devrait être nickel chrome !

Faites-moi signe si y'a d'autres bugasses ou si tout baigne de votre côté.

Allez, portez-vous bien, et merci pour votre patience, les potos !

A la revoyure,
[MisterRobot42]
